### ISSUE TITLE
ember-wormhole failed to render into '#ember-basic-dropdown-wormhole' because the element is not in the DOM

### ISSUE THREAD

**Issue by sarus** [cibernox/ember-power-select-with-create#27]
Tried this addon out for the first time (`v0.1.10`) and I'm getting the error:

```
ember-wormhole failed to render into '#ember-basic-dropdown-wormhole' because the element is not in the DOM
```

Followed by lots of deprecation warnings

```
DEPRECATION: A property of <neon-tetra@view:-outlet::ember454> was modified inside the didInsertElement hook. You should never change properties on components, services or models during didInsertElement because it causes significant performance degradation. [deprecation id: ember-views.dispatching-modify-property]
```

I'm not sure what additional info you would need so please let me know if there is something I can provide to help.

Everything worked fine when using plain `ember-power-select`.  Here is how I have the component setup in the template:

```
  {{#power-select-with-create
    multiple=true
    search=(action "searchRepo")
    selected=selected
    oncreate=(action "createTag")
    onchange=(action (mut selected))
  as |tag|
  }}
    {{tag.tagName}}
  {{/power-select-with-create}}
```

I'm using the following versions of Ember and Ember Data:

```
Ember             : 2.3.1
Ember Data        : 2.3.3
jQuery            : 2.1.4
```

**Comment by sarus** [comment]
Took a look at the tests and it looked like they were setting `renderInPlace=true`.  That seems to have solved the issue.  Is that required for this addon to work properly?

Thanks!

**Comment by felixkiss** [comment]
No, it should work without `renderInPlace` as well. But obviously rendering in place avoids some kind of problem with `ember-wormhole` that you seem to have. Which version of EPS/EPS-with-create are you using?

**Comment by mszoernyi** [comment]
Just ran into the same issue this weekend but for my case I needed a `renderInPlace` anyway.

@sarus `renderInPlace` skips the usage of the wormhole thats why the error is not thrown.

@felixkiss I'm using `0.1.10`

**Comment by sarus** [comment]
I was using ember-power-select-with-create `v0.1.10`.  When I don't use `renderInPlace` there is no `#ember-basic-dropdown-wormhole` in the DOM so I get the wormhole error which probably leads to the deprecation warning.

**Comment by sarus** [comment]
Could this be related to this issue over on the `ember-power-select` issues?

https://github.com/cibernox/ember-power-select/issues/145

**Comment by cibernox** [comment]
Yes. Do you have ember-basic-dropdown listed in your package.json? It must be a direct dependency of your app.

**Comment by sarus** [comment]
Hmm, no I don't have `ember-basic-dropdown` listed in my package.json.

**Comment by Datamance** [comment]
<img width="525" alt="screen shot 2016-07-28 at 8 16 58 am" src="https://cloud.githubusercontent.com/assets/8699411/17218221/e7c27d1e-549b-11e6-924f-f8accc9bb7aa.png">

And that's even after including ember-basic-dropdown in my build.

I started getting this error very suddenly, I think after a restart (I was having problems with watchman). Any idea wtf could be going on here?

**Comment by mrukas** [comment]
I experienced the exact same problem. Shouldn't it be mentioned that `ember-basic-dropdown` needs to be installed? I couldn't find this information on the README page.

**Comment by cibernox** [comment]
@mrukas Well, ember-basic-dropdown doesn't *need* to be installed because it's a runtime dependency of ember-power-select, so it gets installed automatically anyway.

**Comment by mrukas** [comment]
Sorry for answering this late. My `index.html `looks pretty standard. The only thing that solved this problem for me was installing `ember-basic-dropdown`. I'm not sure why this is actually needed, because it already has been installed as dependency of EPS. Adding `<div id="ember-basic-dropdown-wormhole"></div>` to my `index.html` should also solve this problem, am i'm right?

**Comment by cibernox** [comment]
@mrukas are you perhaps building an addon, not an app? I'd love to help you debug this since it shouldn't happen and it doesn't for most people.

**Comment by cibernox** [comment]
@mrukas are you perhaps building an addon, not an app? I'd love to help you debug this since it shouldn't happen and it doesn't for most people.

**Comment by cibernox** [comment]
I have a suspected actually. I'll check later today

**Comment by cibernox** [comment]
@mrukas I think I've found the problem. I did not occur to me that you were using `ember-power-select-with-create` without `ember-power-select` being another direct dependency of the app. I bet that this was your problem.

I've updated the addon so now it can be used that way. Update to v0.2.3 and it should be fixed.
I've also applied this same fix to `ember-power-select-typeahead` and `https://github.com/cibernox/ember-power-select-with-fallback`

**Comment by mrukas** [comment]
@cibernox Sorry for my long response times. I had the time to check your solution. It **works perfectly.** Thanks for this fix! So does this mean that i just would have had to install the package `ember-power-select`? I actually thought that i wouldn't have to install that package, because i thought it's a dependency of `ember-power-select-with-create`?!

**Comment by cibernox** [comment]
@mrukas You are almost right. For the sake of completion, the reason is that while the code of runtime dependencies of your addons gets installed and is available for your apps without installing them explicitly, the hooks of those addons are not run by ember-cli.

In this addon, it must explicitly call the *contentFor* hook of `ember-power-select`, which in turn explicitly calls the *contentFor* hook of `ember-basic-dropdown`, which is the hook that adds the destination div used by `ember-wormhole`.

The change is simple actually: https://github.com/cibernox/ember-power-select-with-create/commit/3236a6155928ed5a0b43a9af1819b6039350cb7a

If you also install EPS or EBD on their own, the hook will be called twice, but that is OK because I made that hook idempotent.

**Comment by charneykaye** [comment]
Hey team, just adding that I found this thread when in fact I had accidentally introduced *un unclosed `<div>`*  to my app/index.html - and the only noticeable side effect was the failure-to-render of the footer content.
